### ISSUE TITLE
Does not work, returns null values

### ISSUE THREAD

**Issue by imKota** [dweinstein/node-google-play#66] opened 2017-08-25 13:00 UTC
Hello!
Your parser again stopped working.
Works only: App details
Do you plan to fix it?

```
➜  gp-download-info com.skype.raider | jq '.'
{ downloadSize: null,
  signature: null,
  downloadUrl: null,
  additionalFile: [],
  downloadAuthCookie: [],
  forwardLocked: null,
  refundTimeout: null,
  serverInitiated: null,
  postInstallRefundWindowMillis: null,
  immediateStartNeeded: null,
  patchData: null,
  encryptionParams: null,
  gzippedDownloadUrl: null,
  gzippedDownloadSize: null,
  splitDeliveryData: [],
  installLocation: null }
```
Thanks!

**Comment by dweinstein** [comment] 2017-08-25 14:49
it works for me and I cannot reproduce this. what version of the library are you using? also check your ANDROID_ID (device) is checked in properly to google play services.

**Comment by imKota** [comment] 2017-08-25 15:04
@dweinstein 
> what version of the library are you using

latest 4.3.1

I checked my ANDROID_ID, it gives empty values with it if I use the "gp-download-info, gp-download-meta, gp-get-sha1" method. And if you use the method "gp-details" then the data is given.

I checked on the ANDROID_ID of the second device, on it all the methods worked.
It turns out I got a ban? But after all on the phone everything is downloaded.
Any ideas?
p.s. If it's interesting to find out the reason, I can send data to the mail for input, as well as ANDROID_ID.

**Comment by dweinstein** [comment] 2017-08-25 17:15
try setting `DEBUG=gp:api`

**Comment by imKota** [comment] 2017-08-25 17:28
@dweinstein 

```
➜  gp-download-meta com.skype.raider                                                                                                                                                              ruby-2.4.0 
TypeError: Cannot read property 'length' of null
    at unescape (/usr/local/lib/node_modules/google-play-cli/lib/app.js:5:30)
    at decodeDigest (/usr/local/lib/node_modules/google-play-cli/lib/app.js:9:21)
    at signatureToSha1 (/usr/local/lib/node_modules/google-play-cli/lib/app.js:13:10)
    at /usr/local/lib/node_modules/google-play-cli/lib/app.js:41:15
    at tryCatcher (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:638:18)
```

**Comment by imKota** [comment] 2017-08-25 17:34
@dweinstein 

use example:

```
var api = require('gpapi').GooglePlayAPI({
    username: 'my mail',
    password: 'my pass',
    androidId: 'my id'
    // apiUserAgent: optional API agent override (see below)
    // downloadUserAgent: optional download agent override (see below)
});

api.downloadInfo("com.viber.voip").then(console.log);
```

Return error:

```
➜  DEBUG=gp:api                                                                                                                        ruby-2.4.0 
kota@iMac—Kota /usr/local/lib/node_modules/gpapi
➜  node test.js                                                                                                                        ruby-2.4.0 
Unhandled rejection Error
    at handleErr (/usr/local/lib/node_modules/gpapi/lib/api.js:247:31)
    at /usr/local/lib/node_modules/gpapi/lib/api.js:252:18
    at tryCatcher (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/gpapi/node_modules/bluebird/js/release/promise.js:638:18)

```

**Comment by dweinstein** [comment] 2017-08-25 19:00
You ran with DEBUG= but you didn't run the gp-download-info command which is the one you said isn't working?

**Comment by imKota** [comment] 2017-08-25 19:03
@dweinstein 
> You ran with DEBUG= but you didn't run the gp-download-info command which is the one you said isn't working?

The last log from gp-download-info  :)

**Closed** 2017-11-05 06:31 UTC
